# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ad7149aa0fcf4b6a22ad5a7fffc724c26db001097f198f589981c4f7edfeefe8c27f0536a4f1ea9b33ddc28ed5ac2b6d881645ba4382687f1b80fe88c30e9f0

test:
  secret_key_base: ba62c1f94ace0c7c4ec3b52b67cc27d33cc733996af3754da74350e752419ec5ea6cad190ad92cc7820d6e0a5a87d044fff6a92e557b9c01849b26c2a9adc794

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
